### ISSUE TITLE
플러그인 추가 개발 요청

### ISSUE THREAD

**Issue by yceffort-naver** [NaverPayDev/code-style#28]
<img width="334" alt="image" src="https://github.com/NaverPayDev/code-style/assets/158988311/53a85814-40b9-4ac1-b627-7097e0a5972d">

svg 관련 플러그인 몇개가 없는 것 같습니다.

### TODO

- [x] 종속성있는 pie 패키지 이관 
  - [x] svg-manager https://github.com/NaverPayDev/pie/issues/50
- plugin 
  - [x] optimize-svg-components
  - [x] svg-unique-id
